table FactCategorySales
	lineageTag: 2a214d33-db90-4c4c-83aa-eac75d7b8f8c

	column MonthStart
		dataType: dateTime
		formatString: Long Date
		lineageTag: 736b8f3b-f565-48f1-b02c-56b0eed2d4c3
		summarizeBy: none
		sourceColumn: MonthStart

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column StoreID
		dataType: string
		lineageTag: 162bc7a8-e126-4796-a9ea-338c745e1199
		summarizeBy: none
		sourceColumn: StoreID

		annotation SummarizationSetBy = Automatic

	column CategoryID
		dataType: string
		lineageTag: 2fbff432-91b0-4785-99ea-b05ebaf25bc0
		summarizeBy: none
		sourceColumn: CategoryID

		annotation SummarizationSetBy = Automatic

	column NetSales
		dataType: double
		lineageTag: 2fa882b5-39ab-40a7-85fc-a5aa9c6b2aa8
		summarizeBy: sum
		sourceColumn: NetSales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GrossProfit
		dataType: double
		lineageTag: 7f6bad3f-e4ea-4929-a29a-fd2850ab43b5
		summarizeBy: sum
		sourceColumn: GrossProfit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnitsSold
		dataType: int64
		formatString: 0
		lineageTag: 9969359d-9676-49ce-a1e4-44d52ef1d26c
		summarizeBy: sum
		sourceColumn: UnitsSold

		annotation SummarizationSetBy = Automatic

	column WasteValue
		dataType: double
		lineageTag: c83a379d-c515-4bc1-95c6-5c8a9f11b394
		summarizeBy: sum
		sourceColumn: WasteValue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PrivateLabelSales
		dataType: double
		lineageTag: 79fc52b9-e6ac-4f16-aeef-f07b82876e46
		summarizeBy: sum
		sourceColumn: PrivateLabelSales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FactCategorySales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(ProjectPath & "Data\FactCategorySales.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Types = Table.TransformColumnTypes(Headers, {
				        {"MonthStart", type date}, {"StoreID", type text}, {"CategoryID", type text},
				        {"NetSales", type number}, {"GrossProfit", type number}, {"UnitsSold", Int64.Type},
				        {"WasteValue", type number}, {"PrivateLabelSales", type number}}, "en-US")
				in
				    Types

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

